
name: Deploy to UAT

on: workflow_dispatch

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> uat
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: uat
          github_token: ${{ secrets.SYNC_TEST_TOKEN }}